### ISSUE TITLE
blank preview

### ISSUE THREAD

**Issue by dfcollazoscISRIC** [ejpsoil/ejpsoildatahub#22]
Hi @pvgenuchten 

Some items show a blank preview like this one: https://catalogue.ejpsoil.eu/collections/metadata:main/items/64e8a11d-5602-4ad5-b370-e4d396fe218f

Here is the yml: https://github.com/ejpsoil/ejpsoildatahub/blob/main/datasets/countries/Belgium/WRB-Reference-Soil-Groups-250k.yml

**Comment by pvgenuchten** [comment]
![image](https://github.com/user-attachments/assets/33a0a396-3624-42c1-bb79-860564392967)
